name: Build with Meson

on:
  push:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-13, windows-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Install Python and pip dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: update pip 
        run: |
          python -m pip install --upgrade pip
      - name: Install deps
        run: |
          python -m pip install cython numpy setuptools>=76.0.0 wheel build meson-python
        shell: bash
      - name: list deps
        run: |
          python -m pip list
      - name: Install Meson
        run: |
          python -m pip install pipx 
          python -m pipx ensurepath
          pipx install meson ninja 
        shell: bash
      - name: Add pipx bin to PATH (cross-platform)
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "$USERPROFILE\\.local\\bin" >> $GITHUB_PATH
          else
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          fi
        shell: bash
      - name: Prepare MSVC
        if: startsWith(${{ matrix.os }}, 'windows')
        uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Test Meson install
        run: meson --version
      - name: Run Meson
        run: |
          meson setup build 
      - name: Run Ninja
        run: |
          ninja -v -C build
      - name: Run python build
        run: |
          python -m build . 
      - name: List the dist folder 
        run: |
          ls -lahtr dist/*
      - name: Run python install
        run: |
          pip install dist/test_cyice-0.0.1*.whl